2025-01-16 13:07:51,061 INFO    MainThread:29479 [wandb_setup.py:_flush():68] Current SDK version is 0.19.3
2025-01-16 13:07:51,061 INFO    MainThread:29479 [wandb_setup.py:_flush():68] Configure stats pid to 29479
2025-01-16 13:07:51,061 INFO    MainThread:29479 [wandb_setup.py:_flush():68] Loading settings from /home/easy/.config/wandb/settings
2025-01-16 13:07:51,061 INFO    MainThread:29479 [wandb_setup.py:_flush():68] Loading settings from /home/easy/yin/robot_arm/opensource_prj/orin-act-plus/act-plus-plus/wandb/settings
2025-01-16 13:07:51,061 INFO    MainThread:29479 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-01-16 13:07:51,061 INFO    MainThread:29479 [wandb_init.py:_log_setup():598] Logging user logs to /home/easy/yin/robot_arm/opensource_prj/orin-act-plus/act-plus-plus/wandb/run-20250116_130751-sofp69hk/logs/debug.log
2025-01-16 13:07:51,062 INFO    MainThread:29479 [wandb_init.py:_log_setup():599] Logging internal logs to /home/easy/yin/robot_arm/opensource_prj/orin-act-plus/act-plus-plus/wandb/run-20250116_130751-sofp69hk/logs/debug-internal.log
2025-01-16 13:07:51,062 INFO    MainThread:29479 [wandb_init.py:init():714] calling init triggers
2025-01-16 13:07:51,062 INFO    MainThread:29479 [wandb_init.py:init():719] wandb.init called with sweep_config: {}
config: {}
2025-01-16 13:07:51,062 INFO    MainThread:29479 [wandb_init.py:init():745] starting backend
2025-01-16 13:07:51,268 INFO    MainThread:29479 [wandb_init.py:init():749] sending inform_init request
2025-01-16 13:07:51,272 INFO    MainThread:29479 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-01-16 13:07:51,273 INFO    MainThread:29479 [wandb_init.py:init():764] backend started and connected
2025-01-16 13:07:51,275 INFO    MainThread:29479 [wandb_init.py:init():857] updated telemetry
2025-01-16 13:07:51,283 INFO    MainThread:29479 [wandb_init.py:init():889] communicating run to backend with 90.0 second timeout
2025-01-16 13:07:54,574 ERROR   Thread-1 (wrapped_target):29479 [internal_api.py:execute():397] 502 response executing GraphQL.
2025-01-16 13:07:54,574 ERROR   Thread-1 (wrapped_target):29479 [internal_api.py:execute():398] 
2025-01-16 13:08:03,492 ERROR   Thread-1 (wrapped_target):29479 [internal_api.py:execute():397] 502 response executing GraphQL.
2025-01-16 13:08:03,492 ERROR   Thread-1 (wrapped_target):29479 [internal_api.py:execute():398] 
2025-01-16 13:08:20,013 ERROR   Thread-1 (wrapped_target):29479 [internal_api.py:execute():397] 502 response executing GraphQL.
2025-01-16 13:08:20,014 ERROR   Thread-1 (wrapped_target):29479 [internal_api.py:execute():398] 
2025-01-16 13:08:55,496 ERROR   Thread-1 (wrapped_target):29479 [internal_api.py:execute():397] 502 response executing GraphQL.
2025-01-16 13:08:55,496 ERROR   Thread-1 (wrapped_target):29479 [internal_api.py:execute():398] 
2025-01-16 13:09:21,316 ERROR   MainThread:29479 [wandb_init.py:init():918] encountered error: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
2025-01-16 13:09:21,317 ERROR   MainThread:29479 [wandb_init.py:init():1378] error in wandb.init()
Traceback (most recent call last):
  File "/home/easy/anaconda3/envs/act-plus/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1368, in init
    return wi.init(run_settings)
  File "/home/easy/anaconda3/envs/act-plus/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 924, in init
    raise error
wandb.errors.errors.CommError: Run initialization has timed out after 90.0 sec. Please try increasing the timeout with the `init_timeout` setting: `wandb.init(settings=wandb.Settings(init_timeout=120))`.
2025-01-16 13:09:21,326 WARNING MsgRouterThr:29479 [router.py:message_loop():75] message_loop has been closed
